name: tests
on:
  push:
    branches:
    - master
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Test CVMFS docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start a container and run commands
        env:
          docker_image: aperloff/cms-cvmfs-docker:light
        run: |
          chmod +x tests/test_commands.sh
          docker run -v ${PWD}:/code --rm --privileged ${{ env.docker_image }} /bin/bash -c /code/tests/test_commands.sh

