name: tests
on:
  push:
    branches:
    - master
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Test CVMFS docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start a container
        run: docker run --rm --privileged gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cc7-cvmfs /bin/bash -c "ls -l"

